### PR TITLE
Add HTTP proxy routing when making requests

### PR DESCRIPTION
**Pull request by JelleBwns**
TODO:

- Add UI support to add HTTP proxy
- Remove duplicate code from LCU class

### CODE REVIEW

**Comment by maxcutie** [comment]
nice work

**Comment by hawolt** [comment]
need to check integritiy before I can approve since I pushed alot of updates since the pr

**Comment by hawolt** [comment]
I do not see a problem with adding this but I would like to understand the benefit of adding this additional proxy step before approving the PR

**Comment by JelleBwns** [comment]
This allowed me to use a HTTP proxy such as [Burp Suite](https://portswigger.net/burp). In case you don't know it's practically the UI tool you're building here with 1000 more features.

**Comment by hawolt** [comment]
sorry for the late response I didnt get a notifcation on this, since there is now UI yet this would be a deadloop when there i no local proxy running, I'll leave this open though for now since someone else might find this useful if they want to use a third party tool

**Pull request closed without merging**
